DELETE FROM Game WHERE true;
DELETE FROM Developer WHERE true;
DELETE FROM Company_information WHERE true;
DELETE FROM Game_type WHERE true;
DELETE FROM Platform WHERE true;
DELETE FROM Publisher WHERE true;
DELETE FROM payment WHERE true;
DELETE FROM Store WHERE true;
DELETE FROM Game_dev_informations WHERE true;
DELETE FROM Internet WHERE true;

Drop table Game;
Drop table Developer;
Drop table Company_information;
Drop table Game_type;
Drop table Platform;
Drop table Publisher;
Drop table payment;
Drop table Store;
Drop table Game_dev_informations;
drop table Internet;